//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquilino
    {
        public int IdInquilino { get; set; }
        public string NombreCompletoInquilino { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronicoInquilino { get; set; }
        public string DNI { get; set; }
        public int IdPropiedad { get; set; }
    
        public virtual Propiedad Propiedad { get; set; }
    }
}
