//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int IdMantenimiento { get; set; }
        public int FechaSolicitud { get; set; }
        public int FechaFinalizacion { get; set; }
        public int TipoMantenimiento { get; set; }
        public int Costo { get; set; }
        public int Estado { get; set; }
        public int Descripcion_Problema { get; set; }
        public int Id_Propiedad { get; set; }
        public int Propiedad_IdPropietario { get; set; }
    
        public virtual Propiedad Propiedad { get; set; }
    }
}
