//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int IdAdmin { get; set; }
        public int Nombre { get; set; }
        public int Descripcion { get; set; }
        public int Rol_IdRol { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
