//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propiedad()
        {
            this.Contrato = new HashSet<Contrato>();
            this.Inquilino = new HashSet<Inquilino>();
            this.Mantenimiento = new HashSet<Mantenimiento>();
        }
    
        public int IdPropietario { get; set; }
        public int Direccion { get; set; }
        public int Tipo { get; set; }
        public int Area { get; set; }
        public int Num_Habitacion { get; set; }
        public int Precio { get; set; }
        public int Estado { get; set; }
        public int Descripcion { get; set; }
        public int ID_Propietario { get; set; }
        public int Usuario_IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inquilino> Inquilino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
