//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Propiedad = new HashSet<Propiedad>();
            this.Rol1 = new HashSet<Rol>();
        }
    
        public int IdUsuario { get; set; }
        public int Codigo { get; set; }
        public int Passwoard { get; set; }
        public int Nombres { get; set; }
        public int Apellidos { get; set; }
        public int CorreoElectronico { get; set; }
        public int Estado { get; set; }
        public int FechaRegistro { get; set; }
        public int DNI { get; set; }
        public int Celular { get; set; }
        public int RUC { get; set; }
        public int Rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propiedad> Propiedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol> Rol1 { get; set; }
    }
}
